### ISSUE TITLE
Bulgaria (BUL) 1960s Focus Tree

### ISSUE THREAD

**Issue by wbattel4607** [swf541/Cold-War--The-Iron-Curtain#102]

**Comment by RobDaFlob** [comment]
BOI I DONT EVEN WORK HERE



I JUST PUT MY FINE GFX ON THAT HAIRLINE @wbattel4607

**Comment by wbattel4607** [comment]
So... you _do_ work here.

**Comment by swf541** [comment]
This is completed barring testing
