### ISSUE TITLE
Nov. 23 1963 issue

### ISSUE THREAD

**Issue by simcitymoo5** [swf541/Cold-War--The-Iron-Curtain#142]
every time nov. 23 1963  comes (assassination date)  I always get a 1951 legislative election pop-up 
Also, the nov 23 1963 focus won't bypass and I cant get the vice president 

https://steamcommunity.com/sharedfiles/filedetails/?id=1423820843

**Comment by stuffi3000** [comment]
These elections are from Greece and use an image from Brazil. We'll fix it, thanks for reporting! =D

**Comment by swf541** [comment]
coded a potential fix, needs tested
