### ISSUE TITLE
Algerian War with France 1960

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#147]
When France wins Algerian Civil war, it seems to puppet a tiny bit of Land instead of annexing it all 
![image](https://user-images.githubusercontent.com/40052257/41997374-12533440-7a58-11e8-9423-ac910c738a81.png)

**Comment by wbattel4607** [comment]
@SpiritOfUSSR can you try and find out if this happens regularly or if it was just a one-time problem?

**Comment by SpiritOfUSSR** [comment]
Second time I play : Algeria collapses into a Civil War between Boumedienne and Ferhat Abbas ==> Boumedienne wins and then peace treaty happens, ending both Algerian War and Civil War 
![image](https://user-images.githubusercontent.com/40052257/42103427-588aae8a-7bc9-11e8-9418-93e1bd1a3c69.png)

**Comment by SpiritOfUSSR** [comment]
3rd time : Civil War between Ferhat Abbas (socialist) and Pan Arabist. Ferhat Wins 
![image](https://user-images.githubusercontent.com/40052257/42103586-cddba090-7bc9-11e8-95bb-7202607ad398.png)

Then another Civil War triggers between Abbas (socialist) and Boumedienne (reactonnary) because Abbas rules a country where Socialism doesn't exist : 
![image](https://user-images.githubusercontent.com/40052257/42103682-0db7e2c8-7bca-11e8-810b-74b8eaf2a8f4.png)

Then Ferhat Abbas (socialism) wins the other civil war : 
![image](https://user-images.githubusercontent.com/40052257/42103822-974ee572-7bca-11e8-9780-dadd0b1f178f.png)

Then another civil war triggers, lead by the Pan Arabist : 
![image](https://user-images.githubusercontent.com/40052257/42103845-b38fbfe0-7bca-11e8-87cb-be544b9eb146.png)

Ferhat Abbas wins it because it happened in the desert (impassable zone) : 
![image](https://user-images.githubusercontent.com/40052257/42103886-d84053a4-7bca-11e8-94f6-af855059b2f5.png)

Note that each civil war weakens Algeria because they loose each time half their division 

Another civil war triggers : 
![image](https://user-images.githubusercontent.com/40052257/42103924-fd5ae6fe-7bca-11e8-9bae-6c03aede7914.png)


Finally Ferhat Abbas loses against France (because they only had 1 division), but because it was in civil war, the other Algeria takes control (same as game 2) 


Here's the issue : Algeria always goes to civil war because Ferhat Abbas is a Socialist but nobody supports socialism in his country, so either France takes down Algeria while it's in a civil war which leads to this screen (situation 2 or 3) or France takes down Algeria BETWEEN two civil wars and it can annex whatever it wants (but probably not too much because she doesn't want to increase world tension too much)
