### ISSUE TITLE
USSR research slots

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#148]
![image](https://user-images.githubusercontent.com/40052257/41997575-a6945c4c-7a58-11e8-86ba-1f1a40d0ec04.png)
USSR doesn't have enough research slot starting in 1960, comparatively to US. It can only go up to 4; which is very very low

**Comment by SpiritOfUSSR** [comment]
![image](https://user-images.githubusercontent.com/40052257/42126332-0a43ed68-7c87-11e8-87d8-562ae46b37c3.png)
Same Problem with 1949 start !!! It's really awful as you CAN'T manage to do at least the major researches. 5 research slots seems a minimum. 7 or 8 the maximum (counting both 49 and 60 starts)

**Comment by swf541** [comment]
Fixed
