### ISSUE TITLE
1960 Bay of Pigs

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#150]
In 1960, USA can puppet Cuba although Bay Of Pigs Failed (Cuba is commie but is called Republic of Cuba) 
![image](https://user-images.githubusercontent.com/40052257/41999552-25a7d874-7a5e-11e8-907c-37a9b8c3b21d.png)
![image](https://user-images.githubusercontent.com/40052257/42000598-654ef2de-7a61-11e8-90c6-1e0d79c03855.png)

EDIT: it didn't work for USA, 
![Uploading image.png…]()

**Comment by swf541** [comment]
Fixed
