### ISSUE TITLE
US Elections event after 72

### ISSUE THREAD

**Issue by Supermob1** [swf541/Cold-War--The-Iron-Curtain#152]
The elections event of 1976,1980,1984,1988,1992,1996,2000,2004,2008,2012 and 2016 are not fired by IC_Pulse and 00_on_actions files
![captdure](https://user-images.githubusercontent.com/40305706/42118383-00ec42da-7c03-11e8-811c-aaffbc8d8381.PNG)
![capture](https://user-images.githubusercontent.com/40305706/42118384-01040636-7c03-11e8-806a-8c498c1fe359.PNG)

**Comment by swf541** [comment]
coded them in
