### ISSUE TITLE
Ministry of Information

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#156]
As you know, Political Power is the most important thing in this mod to gain ideological influence around the world. No sound player would take Unity Propaganda (which only gives stability) against War Propaganda which gives both War Support and Political Power. 

![image](https://user-images.githubusercontent.com/40052257/42126450-5dc76c92-7c89-11e8-8e95-bd9a1d95eac5.png)

Because Stability is better than War Propaganda I suggest you give a +0.15 PP / Unity Propaganda level ( which is less than the War propaganda but still competitive

**Comment by wbattel4607** [comment]
Yeah I think this needs to be completely rebalanced. We'll discuss it.

**Comment by fleeingmoth** [comment]
This mechanic has been removed
