### ISSUE TITLE
Weird War 

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#171]
Why is these wars going on wtf ? I can't tell where it comes from or since when they go on 
![image](https://user-images.githubusercontent.com/40052257/42133229-800b3b42-7d26-11e8-8e53-5dbddd2cf26f.png)
![image](https://user-images.githubusercontent.com/40052257/42133233-a150c916-7d26-11e8-8a8f-bb331baee2c6.png)

![image](https://user-images.githubusercontent.com/40052257/42133237-b1120ee6-7d26-11e8-90bb-ae0797b1b703.png)

ALL 1960 start

**Comment by stuffi3000** [comment]
The first one is weird indeed, the second and the third are historical, though they should have ended in the 50s
