### ISSUE TITLE
Chinese Generals

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#179]
I feel like 5 PRC generals are not enough for a large army  : If I didn't used the No Division Limit mod, I'd be very frustrated not to be able to use historical PRC generals. 

+ Mao doesn't have portrait as Field Marshal 
![image](https://user-images.githubusercontent.com/40052257/43040187-ce3ee044-8d3d-11e8-98a3-4b1bda809504.png)

**Comment by fleeingmoth** [comment]
Do you have any suggestions for any PRC generals?

**Comment by SpiritOfUSSR** [comment]
https://en.wikipedia.org/wiki/List_of_generals_of_the_People%27s_Republic_of_China#Senior_generals_(shang_Jiang,_1955)[3] : look up here

**Comment by fleeingmoth** [comment]
We are working on the issue

**Comment by fleeingmoth** [comment]
There should be more generals for China now. Thank Edward
