### ISSUE TITLE
Hungarian Revolution

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#184]
I was playing in ahistorical with PRC. Hungary seems to trigger twice a Revolution in 1956 : the first one with some event, the other with the Focus Tree. 
![image](https://user-images.githubusercontent.com/40052257/43080077-20a4ee3a-8e8f-11e8-8699-7d0f0f38e541.png)
![image](https://user-images.githubusercontent.com/40052257/43080083-2b556a80-8e8f-11e8-99b7-3553cd460ef6.png)
![image](https://user-images.githubusercontent.com/40052257/43080090-2e686cb8-8e8f-11e8-8be6-458628f84f43.png)
Another thing I noticed is that the communist regime lead by Rakosi, isn't the one which is in Warsaw Pact. So we have a Socialist Regime in Warsaw Pact who isn't the puppet of of USSR

**Comment by swf541** [comment]
fixed
