### ISSUE TITLE
North Vietnamese Generals

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#188]
![image](https://user-images.githubusercontent.com/40052257/43364483-2cc3ed48-931b-11e8-9bfd-67700c2185b1.png)
I think we should add more North Vietnamese Generals, at least 5, best 10.

**Comment by SpiritOfUSSR** [comment]
Military
Võ Nguyên Giáp was the Vietnamese General in the Vietnam People's Army (NVA), Commander-in-Chief of PAVN and was one of the most prominent military leaders during the war.
Văn Tiến Dũng was a Vietnamese general in the People's Army of Vietnam (PAVN), PAVN chief of staff (1954–1974); PAVN commander in chief (1974–1980); and Socialist Republic of Vietnam defense minister (1980–1986).
Hoàng Văn Thái was the General Staff formed National Army, after holding The first Chief of General Staff of the People's Army of Vietnam.
Nguyễn Hữu An was a general in the Vietnamese People's Army, commander of the 2nd Army Corps.
Lê Trọng Tấn was a general and key figure of the Vietnamese People's Army, he was the deputy commander of the Viet Cong and held senior commands in the Easter Offensive and the Ho Chi Minh campaign.
Hoàng Minh Thảo was a general and military theorist of Vietnamese People's Army and an advisor to the Viet Cong.
Viet Cong (National Liberation Front)
Nguyễn Hữu Thọ was the chairman of the National Liberation Front of South Vietnam.
Hoàng Văn Thái was one of the leading commanders of the National Liberation Front of South Vietnam (1967–1973, during the U.S. buildup in South Vietnam), during the Tet Offensive he was the most senior North Vietnamese Officer in South Vietnam.
Trần Văn Trà was one of the leading commanders of the National Liberation Front of South Vietnam and a member of the Central Committee of the Lao Dong Party.
Tran Do was the deputy commander of the Viet Cong.
Nguyễn Văn Linh was a political leader of the Viet Cong during the Vietnam War who served as party secretary of South Vietnam for Communist Party of Vietnam.
Võ Chí Công was a Vietnamese Communist political figure who was one of the founding members of the Viet Cong.
Huỳnh Tấn Phát chairman of the Provisional Revolutionary Government of the Republic of South Vietnam from 1969 to 1976.

**Comment by fleeingmoth** [comment]
there are 7 vietnam generals in now
