### ISSUE TITLE
Cuba Elections Already chosen

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#192]
## Explain the Problem

The 1948 Elections for Cuba 
![cuba elections 2](https://user-images.githubusercontent.com/36431087/43430169-36027452-942d-11e8-88fd-a764667c58b2.jpg)
have already been selected when I start the game, not sure is this is on purpose or a mistake.

**Comment by ThunderGemios10** [comment]
The game starts in 1949, and according to the focus tree, the Cuban elections have been held in 1948. So it's natural for it to pre-completed. I may be wrong though.
