### ISSUE TITLE
Broken leader names

### ISSUE THREAD

**Issue by Kennelly1** [swf541/Cold-War--The-Iron-Curtain#213]
## Explain the Problem
Several leader names with special characters are broken:
![hoi4_8](https://user-images.githubusercontent.com/33550299/45367675-18510780-b5e2-11e8-88e1-e7bebed9cf0d.png)
![hoi4_7](https://user-images.githubusercontent.com/33550299/45367731-361e6c80-b5e2-11e8-933b-209e9df0be42.png)

**Comment by fleeingmoth** [comment]
these should be fixed: latvia doesn't have that leader and the rest are fixed
