### ISSUE TITLE
Victory point in the ocean

### ISSUE THREAD

**Issue by Kennelly1** [swf541/Cold-War--The-Iron-Curtain#216]
## Explain the Problem
The victory point of Turks and Caicos (Cockburn Turn) is in the middle of the Caribbean Sea, not on the islands.
![hoi4_21](https://user-images.githubusercontent.com/33550299/45371531-25262900-b5eb-11e8-9f07-9ee3ed02992f.png)

**Comment by Kennelly1** [comment]
Similar problem:
![hoi4_32](https://user-images.githubusercontent.com/33550299/45374454-6d951500-b5f2-11e8-823d-fcff0b85dbf6.png)
![hoi4_33](https://user-images.githubusercontent.com/33550299/45374554-c5338080-b5f2-11e8-8dbc-e38d14689441.png)

**Comment by generalisofficial** [comment]
Fixed
