### ISSUE TITLE
USA focus icons problem

### ISSUE THREAD

**Issue by Kennelly1** [swf541/Cold-War--The-Iron-Curtain#223]
## Explain the Problem
Various USA focuses have working icons in the focus tree itself, but not in the country view (probably some issue with the shinemaker?).
![hoi4_9](https://user-images.githubusercontent.com/33550299/45383981-fe78ea00-b60c-11e8-92f4-2d626aaa1223.png)

**Comment by fleeingmoth** [comment]
Yes, problem with shine

**Comment by higuyscd32oof** [comment]
problem fixed
