### ISSUE TITLE
Minor spelling&grammar mistakes

### ISSUE THREAD

**Issue by Kennelly1** [swf541/Cold-War--The-Iron-Curtain#224]
## Explain the Problem

Daily News event "DDR Established": happend-->happened / independen-->independence
USA event "Even More Men needed in Korea": korean-->Korean
Daily News event "The Republic of China on Taiwan": The was has calmed-->The war has calmed
1949 scenario description: asia-->Asia

**Comment by fleeingmoth** [comment]
Republic of China war calmed fixed

**Comment by fleeingmoth** [comment]
DDR established fixed
