### ISSUE TITLE
USSR Effects missing

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#244]
![image](https://user-images.githubusercontent.com/40052257/50489654-2b5cdb80-0a09-11e9-9167-35528a1c3ac8.png)
![image](https://user-images.githubusercontent.com/40052257/50489658-2e57cc00-0a09-11e9-9f13-b588d324705e.png)
![image](https://user-images.githubusercontent.com/40052257/50489662-3283e980-0a09-11e9-8ca9-dfd904c20bf0.png)
![image](https://user-images.githubusercontent.com/40052257/50489671-40d20580-0a09-11e9-9bd5-e7684fb5956d.png)

**Comment by leftwinglow** [comment]
Fixed
