### ISSUE TITLE
Province Serowe owned by Finland

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#259]
Starts like this in my recent games
![20181230152530_1](https://user-images.githubusercontent.com/36431087/50551528-6b110680-0c47-11e9-86b5-203a4937f6d1.jpg)

**Comment by Kreunz** [comment]
Did you load a older save?

**Comment by generalisofficial** [comment]
Its a implausible finnish event that tries to give the old borders back but they were deleted for having gay
