### ISSUE TITLE
AK 47

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#263]
Why not make the AK-47 a specific weapon, available only for USSR, which cost less than the other similar tech, that could be licensed by USSR and really make it significant to sell.
![image](https://user-images.githubusercontent.com/40052257/50551910-18583e80-0c89-11e9-9802-b5f2d31bb865.png)

**Comment by generalisofficial** [comment]
This is not an issue, this is a suggestion
