### ISSUE TITLE
Heavy S-P Artillery Problem

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#268]
Unable to edit/remove unit(s) of Heavy S-P Artillery after placing them into a template
![20181230191254_1](https://user-images.githubusercontent.com/36431087/50553179-0bc2ee80-0c67-11e9-928e-6862d664235f.jpg)
.

**Comment by leftwinglow** [comment]
Could not be replicated, presumed fixed
