### ISSUE TITLE
Miscellaneous Suggestions

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#282]
- If you went down the Soviet/American tree with your country, and you choose the opposite on the 60's focus tree it should remove the bonus effects given by the other (ie American improvements go away if you choose Soviets next).
- What is the point of using light tanks for speed if not even Motorized or Mechanized can keep up with them? I would suggest a higher max speed for either.
![20190102073019_1](https://user-images.githubusercontent.com/36431087/50594017-6d01e200-0e60-11e9-8510-57ddd4959860.jpg)
![20190102073109_1](https://user-images.githubusercontent.com/36431087/50594019-6ffcd280-0e60-11e9-808d-c89476a94959.jpg)
![20190102073119_1](https://user-images.githubusercontent.com/36431087/50594023-71c69600-0e60-11e9-98a2-eae2bba3136a.jpg)
- Implement some way to see more than 20 National Spirits
![20190102075320_1](https://user-images.githubusercontent.com/36431087/50594806-98d29700-0e63-11e9-9b85-a469fd3ad773.jpg)
- Either reintegrate advisers to promote any political party or have some way to promote them via decisions, as their are little to no focuses or NS's (National Spirits) that compensate. if having every nations have the potential to promote any ideology seems ridiculous, I would at least suggest hand picking each nation for which ideology(s) that can promote
- Changing the bonus given by this Industry if we have to wait for it by 78' as the already provided one has a higher bonus than the former mentioned one.
![20190102154814_1](https://user-images.githubusercontent.com/36431087/50614328-fab3f080-0ea5-11e9-9710-f30738056148.jpg)
![20190102154811_1](https://user-images.githubusercontent.com/36431087/50614331-fe477780-0ea5-11e9-95a9-850606a70efc.jpg)
- Same suggestion for these two industry choices
![20190102160710_1](https://user-images.githubusercontent.com/36431087/50615040-90507f80-0ea8-11e9-9fb2-76e423169057.jpg)
![20190102160709_1](https://user-images.githubusercontent.com/36431087/50615043-92b2d980-0ea8-11e9-9b47-ae313bc780c9.jpg)
- Give East Germany more options to avoid being reintegrated without permission, too many games just end with them

**Comment by higuyscd32oof** [comment]
no suggestions
