### ISSUE TITLE
Repeating Events

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#288]
- Treaty of Taipei
![20190102134321_1](https://user-images.githubusercontent.com/36431087/50609203-9ccadd00-0e94-11e9-9007-8341a46a4131.jpg)
- An Uprising in Berlin!
![20190102154333_1](https://user-images.githubusercontent.com/36431087/50614118-66e22480-0ea5-11e9-85fb-93e5ae588606.jpg)

**Comment by higuyscd32oof** [comment]
problem fixed
