### ISSUE TITLE
Uganda 50's Focus  Tree Problems

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#296]
- UGA?Constitutional?Monarchy Focus remains The Kingdom of Uganda "The Kingdom of The Kingdom of Uganda"
![20190109224636_1](https://user-images.githubusercontent.com/36431087/50946784-afc74980-1460-11e9-8902-70b3c269accb.jpg)

**Comment by higuyscd32oof** [comment]
unfixable bug
