### ISSUE TITLE
Israel 50's Focus Tree Problems

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#299]
- Choosing "American Alignment" still lets you able to pick "Armed Neutrality"
![20190115170027_1](https://user-images.githubusercontent.com/36431087/51215658-42e00380-18e7-11e9-8f1c-b841b3a7c3f1.jpg)

**Comment by Flizzyclone** [comment]
Focus no longer exists in focus tree rework
