### ISSUE TITLE
Israel Suggestions

### ISSUE THREAD

**Issue by BearGlitch1** [swf541/Cold-War--The-Iron-Curtain#300]
- Obvious advantageous choice between these two "Tank Designers"
![20190115170503_1](https://user-images.githubusercontent.com/36431087/51215866-f0ebad80-18e7-11e9-9655-a69c80fe5f07.jpg)
![20190115170501_1](https://user-images.githubusercontent.com/36431087/51215868-f34e0780-18e7-11e9-8a81-4bbd707defbe.jpg)

**Comment by higuyscd32oof** [comment]
company removed
