### ISSUE TITLE
Some aircraft techs have case-insensitive file paths

### ISSUE THREAD

**Issue by wbattel4607** [swf541/Cold-War--The-Iron-Curtain#42]
For example:
![capture](https://user-images.githubusercontent.com/13490339/40884085-dab24e42-66d2-11e8-8b88-65caa8537c2a.PNG)
but there are more as well.

Their file paths must be made case-sensitive to function properly on Steam.

**Comment by NikoESKUBI** [comment]
Happend the same to the Spanish Air Force, I made the gfx and just can see maybe less than a half

**Comment by wbattel4607** [comment]
@NikoESKUBI which planes are missing from Spain?

**Comment by NikoESKUBI** [comment]
@wbattel4607 , Battleman say that the problem is they’re using the old name scheme

**Comment by NikoESKUBI** [comment]
Close to half of them

2018-06-04 6:04 GMT+02:00 Will Battel <notifications@github.com>:
