### ISSUE TITLE
AI assigning invalid air missions

### ISSUE THREAD

**Issue by wbattel4607** [swf541/Cold-War--The-Iron-Curtain#43]
Strategic Bombers can't do Air Superiority or CAS missions but somehow the AI selected them anyway. The buttons are grayed out and can't be clicked, but the AI does it anyway.

![bug](https://user-images.githubusercontent.com/13490339/40892873-2622aa40-6762-11e8-9a42-df0555520a8b.PNG)

**Comment by stuffi3000** [comment]
There is an entry in the error log for this issue, I just don't remember is right now (I'll get back to it)

**Comment by wbattel4607** [comment]
@stuffi3000 I see this `AI tried to post an invalid command: deploy_air_wing_command` is that what you're talking about?

**Comment by stuffi3000** [comment]
Exactly @wbattel4607

**Comment by wbattel4607** [comment]
@stuffi3000 I have no idea what is causing that.

**Comment by stuffi3000** [comment]
Thank you Paradox (Not): https://forum.paradoxplaza.com/forum/index.php?threads/error-ai-assiging-invalid-air-missions.1109352/

**Comment by swf541** [comment]
Pdox issue not ours
