### ISSUE TITLE
Cuban missile Crisis 1949 => Minor 60's Focus Tree not switching in 1960 with a 1949 game ?

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#56]
Cuban FT is changed to a generic one after 1960, when starting in 1949, therefore Cuban Missile Crisis can't trigger 

Laos 60's FT is a generic one in 49's game : 
![image](https://user-images.githubusercontent.com/40052257/41170744-f30983d2-6b4d-11e8-8c70-77c80f926d3b.png)

**Comment by swf541** [comment]
This is not a bug
