### ISSUE TITLE
South Korea / Israel 

### ISSUE THREAD

**Issue by SpiritOfUSSR** [swf541/Cold-War--The-Iron-Curtain#58]
With a friend, we did a game starting in 49. He plays Israel and I play USA. He attacked Syria for Golan. They white peaced when Syria collapsed and we saw nothing changed : Golan was still property of Syria even though it was claimed by Israel. 

Later on we saw that Israel had a territory in Reunited South Korea. I can't say from when he had it but I'd go for this white peace thing. 
![image](https://user-images.githubusercontent.com/40052257/41179436-feef6a3c-6b6a-11e8-8429-e31288629451.png)

**Comment by stuffi3000** [comment]
Not sure which event caused it, but the map thing is because of Generalis' state transfer stuff that hasn't been implemted into all events yet

**Comment by generalisofficial** [comment]
I havent changed south korea

**Comment by stuffi3000** [comment]
It's just a wrong state ID in the event file then
