### ISSUE TITLE
Dutch East Indies missing name

### ISSUE THREAD

**Issue by wbattel4607** [swf541/Cold-War--The-Iron-Curtain#66]
## Explain the Problem

Seen at beginning of 1949 start date.

![capture](https://user-images.githubusercontent.com/13490339/41211534-87216958-6cfd-11e8-93e1-d9c2127ba950.PNG)

**Comment by generalisofficial** [comment]
Swf's cosmetic tag cancer for INO = cause

**Comment by wbattel4607** [comment]
Fixed in 0c66639cf02cae7e0a7e02fc9a1c0e615a2c09e9 and cherry-picked in 2d9f873f55d2a2c8e486c34eb8e0028ae360b072
