### ISSUE TITLE
US Flag difference

### ISSUE THREAD

**Issue by Supermob1** [swf541/Cold-War--The-Iron-Curtain#72]
## Explain the Problem
US Flag is different for progressive and conservatism party
![conservative](https://user-images.githubusercontent.com/40305706/41488343-488054f0-70ec-11e8-950c-b4053444c5ad.PNG)
![progressive](https://user-images.githubusercontent.com/40305706/41488344-489b18d0-70ec-11e8-9769-dbf8a1c86f7d.PNG)

**Comment by generalisofficial** [comment]
Both should be the first one
