### ISSUE TITLE
World War Three very rarely starts without Human Player intervention

### ISSUE THREAD

**Issue by wbattel4607** [swf541/Cold-War--The-Iron-Curtain#73]
## Explain the Problem

Without the Player getting involved, the AI very rarely starts a global conflict. It should be more likely to happen, as IRL the Cold War was very frequently on the edge of going hot.

Currently, many nations such as PRC, UK, and India get war goals on multiple countries that would escalate. However, the AI never execute their war goals.

Another example, the USSR never picks the "World War 3" national focus. They frequently get all of the prerequisites but they never finish the branch.

**Comment by generalisofficial** [comment]
is that a bad thing?

**Comment by stuffi3000** [comment]
The AI doesn't execute them because it's not capable of going to Defcon 3 and declare war

**Comment by wbattel4607** [comment]
@generalisofficial yes.

@stuffi3000 the weird thing is that they actually are going to low DEFCON. I went into observer mode and checked them out and they were all at DEFCON 3 or lower (maybe from focuses or events), and capable of declaring war (the Declare War button was available), but for whatever reason they aren't doing it.

**Comment by wbattel4607** [comment]
Fix attempts in 826f4ef and ffe3af3

**Comment by stuffi3000** [comment]
@wbattel4607 Hm weird. The ai_agressive could really help though
