### ISSUE TITLE
British Decolonisation tree and event

### ISSUE THREAD

**Issue by Supermob1** [swf541/Cold-War--The-Iron-Curtain#87]
## Explain the Problem
50s British Focus Tree Decolonisation don't work, both focus have the same effects and invalid event
![dec](https://user-images.githubusercontent.com/40305706/41628987-4509bac6-7427-11e8-9d2b-6ac1d2fbedbf.PNG)
![dec2](https://user-images.githubusercontent.com/40305706/41628989-487c0538-7427-11e8-83bf-859296957159.PNG)

**Comment by wbattel4607** [comment]
Closing ahead of changes coming in #89
