### ISSUE TITLE
financial reserves

### ISSUE THREAD

**Issue by tomasport26** [swf541/Cold-War--The-Iron-Curtain#88]
hi i been playing some nations like argentina or other minor and i dont getting financial reserves from industrial or taxes and i see that the first day of the start of the game i got 0.1 from tax nothing from industrial and the next day i got 0 per day and the mayor nations gets a whole like us 164 and ussr 166 per day from the start and there goes i see if some mod do i have but just yours and nothing is the same and i see like putting a whole bunch of industrial and i start from a day to another getting 30 per day and i dont know
thanks

**Comment by wbattel4607** [comment]
@tomasport26 we've recently fixed this issue and it will be available in the next version!
